import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ display: "flex", flexDirection: "column", height: "100vh" }}
      >
        <nav style={{ backgroundColor: "black", color: "white" }}>Navbar</nav>
        <main style={{ flex: "1" }}>{children}</main>
        <footer style={{ backgroundColor: "red", color: "white" }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
